create TABLE users(
    id SERIAL PRIMARY KEY,
    name CHARACTER VARYING (50) NOT NULL,
    lastname CHARACTER VARYING (50) NOT NULL,
    patronymic CHARACTER VARYING (50) NOT NULL,
    age INTEGER,
    phone CHARACTER VARYING (50) NOT NULL,
    login CHARACTER VARYING (50) NOT NULL,
    password INTEGER NOT NULL,
    post CHARACTER VARYING (50) NOT NULL
);